### ISSUE TITLE
Error: Index out of range

### ISSUE THREAD

**Issue by n-truongnx** [fukaoi/solana-suite#173]
i try to use function Metaplex.feePayerPartialSignMint but i hit that error:
`
error: RangeError: Index out of range
`
this is my code
<img width="827" alt="Screen Shot 2023-04-21 at 16 05 52" src="https://user-images.githubusercontent.com/121841837/233595250-10560178-297d-402a-8911-f29ed799d5d9.png">

- nftUrl is a s3 link
- secret is privateKey of payer

<img width="1418" alt="Screen Shot 2023-04-21 at 16 04 54" src="https://user-images.githubusercontent.com/121841837/233595021-f51f7686-7674-455f-bc75-acd406f46651.png">

what wrong with my code? pls help

**Comment by fukaoi** [comment]
What is your development environment?

Are you trying to run on React.js?

What version of Solana Suite are you running?

**Comment by n-truongnx** [comment]
yeah, i am trying on Reactjs.
i work on macos
this is my package.json
<img width="339" alt="Screen Shot 2023-04-21 at 22 03 00" src="https://user-images.githubusercontent.com/121841837/233669605-14d1aba3-f044-48d5-b68c-4feb3b033098.png">

**Comment by fukaoi** [comment]
@n-truongnx 
Thanks response.

I have created a sample repository of [react.js here](https://github.com/fukaoi/react-solana-suite). It works fine, so it does not seem to be a Solana Suite issue.

> Exmple code react-solana-suite/src/App.js
```js
import { Metaplex } from '@solana-suite/nft';

const demoOwner = 'Hh7nDDB8nNY2QcQLHG5SdVKXd6Q3ZpiT5CBxnxCxjkDp';
const demoSecret =
  '4GXGESeUqw75z9iUyvUrFoCFMMRaDaS3XXKsuVcQJEcd2wGFgUcqVivtNAJmZ7o3KbmzsRaBLTVs48rXXaA7mSeE';
const demoPayer = 'H7WEabRV8vvCJxK8forAUfeXunoYpWFbhewGj9eC4Pj8';
const demoPayerSecret =
  '4DRpsEkwfAMc7268urkNu2AFC4tweXTLJArwXG9LGvjqcFUoy9mqmBZHLhf2yHEbj3AgrjVppEBQ5hfBTnDzLVSA';

const demoInput = {
  name: 'name',
  symbol: 'VE',
  royalty: 5,
  uri: 'https://ipfs.io/ipfs/bafkreiczvsz3siw62qium44l27nm24lg5foftpogjyav23fdbvrltrewrm',
};

(async () => {
  const inst = await Metaplex.feePayerPartialSignMint(
    demoOwner,
    demoSecret,
    demoInput,
    demoPayer
  );
  console.log(inst);

  const res = await inst.unwrap().submit(demoPayerSecret);
  console.log(res.unwrap().toExplorerUrl());
})();

function App() {
  return <div className="App"></div>;
}

export default App;
```

It may be an issue with the React.js dependent libraries. You may want to compare it with this [package.json.](https://github.com/fukaoi/react-solana-suite/blob/main/package-lock.json)

React.js (webpack) and crypto library are not compatible. :sweat_smile: 

![Screenshot from 2023-04-22 09-32-11](https://user-images.githubusercontent.com/186659/233752759-371005cb-95a2-4ca2-81dc-a63c246b344f.png)

**Comment by ken-z-dev** [comment]
Ak sorry, it seem like uri too long, i just change uri to a shorter s3 url and it run ok.
pls close this issuse,
Many thanks

**Comment by fukaoi** [comment]
Oh, So good!
closed
