### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by moeidsaleem** [fukaoi/solana-suite#237]
No Typescript support, couldn't find types.

**Comment by fukaoi** [comment]
@moeidsaleem 

thank you comment.

>No Typescript support, couldn't find types.

 We do provide necessary functionalities through '.d.ts' files.

[ref]
https://github.com/fukaoi/solana-suite/blob/main/packages/suite-compressed-nft/dist/index.d.ts

could you provide a bit more context or information?"
