### ISSUE TITLE
Phantom wallet flags your website

### ISSUE THREAD

**Issue by thekesslereffect** [fukaoi/solana-suite#239]
For some reason Phantom wallet is flagging all of your websites.
![image](https://github.com/fukaoi/solana-suite/assets/24286691/2853449a-ca53-4cb8-903a-5f67ed02133b)

**Comment by fukaoi** [comment]
Thank you

The tool at https://smt.solana-suite.org/ has been blacklisted, and as a result, the entire domain is now blacklisted. I have been in communication with the person in charge of issues at Phantom, and we need to make modifications to smt.solana-suite.org. However, I have been quite busy and haven't had the chance to make these changes.
